### ISSUE TITLE
Remove notice from IzzyOnDroid repo about lack of updates

### ISSUE THREAD

**Issue by superuser-does** [lorenzovngl/FoodExpirationDates#102]
I'm a new user thanks to Food Expiration Dates being advertised within my F-Droid app.

After checking, I believe the [notice about no further updates](https://apt.izzysoft.de/fdroid/index/apk/com.lorenzovainigli.foodexpirationdates.foss/) can now be removed, since the versions are 2.0 both here and on the repository.

**Comment by lorenzovngl** [comment]
The notice has been removed
