### ISSUE TITLE
Translation for Tamil

### ISSUE THREAD

**Issue by Maha-Rajan** [lorenzovngl/FoodExpirationDates#115]
Hello I can contribute translation for my native language Tamil. How can be part of this?

**Comment by lorenzovngl** [comment]
Hello!

Contributions are welcome here, please read [_Contributing to Food Expiration Dates_](https://github.com/lorenzovngl/FoodExpirationDates/blob/main/CONTRIBUTING.md) to know how to do your contribution, and if you have further questions, feel free to ask here.

Thank you 😊
