### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by saltsoftdrink** [lorenzovngl/FoodExpirationDates#125]
Which library did you used for this - https://github.com/devedroy/FoodExpirationDates/blob/main/screenshots/en/screen_4.png

**Comment by lorenzovngl** [comment]
Hello, I used [Jetpack Compose's Bottom sheets](https://developer.android.com/jetpack/compose/components/bottom-sheets)

**Comment by saltsoftdrink** [comment]
> Hello, I used [Jetpack Compose's Bottom sheets](https://developer.android.com/jetpack/compose/components/bottom-sheets).
> 
> Please use the [Discord server](https://discord.gg/vV98jT2umw) to ask questions like this.

I'm asking for the clock
