### ISSUE TITLE
Spanish translation missing

### ISSUE THREAD

**Issue by lorenzovngl** [lorenzovngl/FoodExpirationDates#13]
I would like to add a Spanish translation to this app.

To solve this issue:

1. comment below requesting the assignment and wait my reply;
1. fork the project and create a new branch, then checkout to the new branch;
1. work on the new translation (in alternative you can use the translation editor as [described here](https://developer.android.com/studio/write/translations-editor)):
    1. create the folder `value-es` under `app/src/main/res`;
    1. create in the new folder the file `strings.xml` copied from [the default strings.xml](https://github.com/lorenzovngl/FoodExpirationDates/blob/main/app/src/main/res/values/strings.xml);
    1. translate each string to Spanish;
1. commit your changes (please use the convention of [gitmoji.dev](https://gitmoji.dev/) as other commits in this project);
1. open a pull request with the main branch of this repo as target.

**Comment by Quadropo** [comment]
Hi Lorenzo. Im a Native Spanish Freelance Translator and Localization Specialist English🔄Spanish. Over 3 years of experience. I will love to help you😊

**Comment by lorenzovngl** [comment]
Hi @Quadropo, thank you for reaching me!
There is a further step to do (I'm sorry, I forgot to add it before):

- [ ] I accept the [Code of Conduct](https://github.com/lorenzovngl/FoodExpirationDates/blob/main/CODE_OF_CONDUCT.md).
- [ ] I accept the [Contribution Guidelines](https://github.com/lorenzovngl/FoodExpirationDates/blob/main/CONTRIBUTING.md).

Please answer to this message pasting the two lines above with checkmarks checked as sign of acceptance of Code of Conduct and Contribution Guidelines 🙂

**Comment by Quadropo** [comment]
Can you pls check your Twitter DMs

**Comment by Quadropo** [comment]
> 

I accept the [Code of Conduct](https://github.com/lorenzovngl/FoodExpirationDates/blob/main/CODE_OF_CONDUCT.md).
 I accept the [Contribution Guidelines](https://github.com/lorenzovngl/FoodExpirationDates/blob/main/CONTRIBUTING.md).
