### ISSUE TITLE
Interacting with Greyed-out fields

### ISSUE THREAD

**Issue by d-realblank** [lorenzovngl/FoodExpirationDates#142]
**Description**
Greyed-out fields like the unchecked Opening Date can still be interacted with.

**To Reproduce**
1. Go to 'Lists'
2. Click on '+'
3. Click on 'Opening Date' without checking the checkbox

**Expected behavior**
No registered interactions

**Observed Behavior**
Interaction is possible
![Screenshot_20240416_130342](https://github.com/lorenzovngl/FoodExpirationDates/assets/61207991/7ee10ff1-8df2-49c5-a239-043bd60f05d2)
![Screenshot_20240416_130658](https://github.com/lorenzovngl/FoodExpirationDates/assets/61207991/ddfcd623-3248-47c5-b724-c13368b06057)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - IDE: Android Studio
 - Version: 2023.2.1 Patch 2

**Smartphone (please complete the following information):**
 - Device: Pixel 3a
 - OS: Android 14

**Additional context**
This bug does not affect the item as the opening date is only used when the box is checked

**Comment by lorenzovngl** [comment]
Thank you for pointing out this bug!
