### ISSUE TITLE
Change order of options.

### ISSUE THREAD

**Issue by Dtrieb** [lorenzovngl/FoodExpirationDates#187]
Can you change the order of this Buttons to:

Liste // Einstellungen // Über diese App
List // Settings // About this App

![Screenshot_20240703-124523](https://github.com/lorenzovngl/FoodExpirationDates/assets/3650284/fee3e2d3-ed66-415c-b8b6-2cb4e4d6259f)

**Comment by anuragkanojiya1** [comment]
Assign me this under hacktoberfest
