### ISSUE TITLE
[Feature] Opening Date

### ISSUE THREAD

**Issue by EIIEss** [lorenzovngl/FoodExpirationDates#65]
For a lot of products the opening date is also an important information.  
It would be great to have the ability to enter an opening date as well as a time span for how long the item is good after opening.
These two fields should be optional. If both fields are filled, the item will be listed according to the opening date + time span in the expirations list. Otherwise the original expiration date will be used for sorting.

**Comment by lorenzovngl** [comment]
Sounds very good, I will implement it as soon as possible.
Thank you for the suggestion!

**Comment by Aditya-Mi** [comment]
i want to work on this issue please assign.

**Comment by lorenzovngl** [comment]
Closed as completed by https://github.com/lorenzovngl/FoodExpirationDates/commit/c6dd894f1cd77a66964449b2063ee9f996687251
