### ISSUE TITLE
List of contributors inside the app

### ISSUE THREAD

**Issue by lorenzovngl** [lorenzovngl/FoodExpirationDates#67]
It will be good to see the list of contibutor inside the app. I think the best place to insert their names is at the bottom of [InfoActivity](https://github.com/lorenzovngl/FoodExpirationDates/blob/main/app/src/main/java/com/lorenzovainigli/foodexpirationdates/view/activity/InfoActivity.kt).

My idea is to create a list like this:

### Contributors
Thanks to these awesome people for contibuting to the development of this app. 
- John Doe (@_johndoe)
- ...

**Comment by DeKaN** [comment]
Hi, can I take the issue? Also, can you add more information about source of contributor list for the app?

**Comment by lorenzovngl** [comment]
Yes, I assign it to you.
You can find the contributor list in [README](https://github.com/lorenzovngl/FoodExpirationDates#-contributors)
