### ISSUE TITLE
Replace Accompanist System UI Controller with Edge-to-Edge

### ISSUE THREAD

**Issue by lorenzovngl** [lorenzovngl/FoodExpirationDates#72]
As stated [here](https://google.github.io/accompanist/systemuicontroller/), Accompanist System UI Controller library is deprecated.

The library must be removed from this project, replacing it with Edge-to-Edge component as explained in [this video](https://www.youtube.com/watch?v=pLMw9Vlbfgw).

**Comment by AdityaKumdale** [comment]
Hey @lorenzovngl, I am  working on it.

**Comment by lorenzovngl** [comment]
Thank you!

**Comment by AdityaKumdale** [comment]
Hey @lorenzovngl please check the pull request.

**Comment by AdityaKumdale** [comment]
Thanks @lorenzovngl as a  pre-intermediate in Compose I am very happy you reviewed my pr. I will  actively start to work on all your suggestions and make a new pr. This is one of the best repos I came across hacktoberfest this year.

**Comment by AdityaKumdale** [comment]
Hey @lorenzovngl please check the pull request.

**Comment by lorenzovngl** [comment]
> Thanks @lorenzovngl as a pre-intermediate in Compose I am very happy you reviewed my pr. I will actively start to work on all your suggestions and make a new pr. This is one of the best repos I came across hacktoberfest this year.

I'm happy to review code of others developers, it helps me to think about different ways to implement the solutions.
Thank you very much for your words!

**Comment by AdityaKumdale** [comment]
Hey @lorenzovngl please check the pr conversation again I made latest commit in it.
